# Generated by Django 5.2 on 2025-12-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('max_invited', models.IntegerField()),
                ('country', models.CharField(help_text='ISO code (e.g. PT or ES)', max_length=2)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.IntegerField()),
                ('getting_places_1', models.CharField(max_length=100)),
                ('getting_places_2', models.CharField(blank=True, max_length=100)),
                ('getting_places_3', models.CharField(blank=True, max_length=100)),
                ('getting_places_4', models.CharField(blank=True, max_length=100)),
                ('getting_places_5', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('start_dt', models.DateTimeField()),
                ('finish_dt', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
            },
        ),
    ]
