# Generated by Django 5.2 on 2026-01-01 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parties',
            name='users',
        ),
        migrations.AddField(
            model_name='parties',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parties',
            name='ghosts',
            field=models.ManyToManyField(related_name='ghosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parties',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
