# Generated by Django 5.2 on 2026-01-01 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_remove_parties_users_parties_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='ghosts',
            field=models.ManyToManyField(blank=True, null=True, related_name='ghosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
