# Generated by Django 5.2 on 2026-01-04 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_alter_parties_ghosts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='ghosts',
            field=models.ManyToManyField(blank=True, related_name='party_ghosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
