# Generated by Django 5.2 on 2026-01-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_alter_parties_ghosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='country',
            field=models.CharField(choices=[('PT', 'Pt'), ('ES', 'Es')], help_text='ISO code (e.g. PT or ES)', max_length=2),
        ),
    ]
