# Generated by Django 5.2 on 2026-01-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_alter_parties_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='country',
            field=models.CharField(choices=[('PT', 'PT'), ('ES', 'ES')], help_text='ISO code (e.g. PT or ES)', max_length=2),
        ),
    ]
