# Generated by Django 5.2 on 2026-01-09 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_priceoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spots_taken', models.IntegerField(default=0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='parties.parties')),
            ],
        ),
        migrations.DeleteModel(
            name='PriceOptions',
        ),
    ]
