# Generated by Django 5.2 on 2026-01-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0009_partyprices_delete_priceoptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partyprices',
            options={'verbose_name': 'Party Price', 'verbose_name_plural': 'Party prices'},
        ),
    ]
