# Generated by Django 5.2 on 2026-01-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0010_alter_partyprices_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Option Price',
            },
        ),
        migrations.CreateModel(
            name='PartyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.parties')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.optionprices')),
            ],
            options={
                'verbose_name': 'Party Price',
            },
        ),
        migrations.DeleteModel(
            name='PartyPrices',
        ),
    ]
