# Generated by Django 5.2 on 2026-01-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0012_alter_parties_created_by_alter_partyprice_party_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='partyprice',
            name='party',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='party_price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='party',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user_created',
        ),
        migrations.DeleteModel(
            name='OptionPrices',
        ),
        migrations.DeleteModel(
            name='PartyPrice',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
