# Generated by Django 5.2 on 2025-12-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axceptnotifications',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
